### ISSUE TITLE
Bookmarks popup broken

### ISSUE THREAD

**Issue by ArataKamikaze** [lr-tech/OnelineProton#1]
when you try to add a page to the bookmarks, the popup looks like this
![image](https://user-images.githubusercontent.com/49700094/129250219-f2167ebd-7697-4da6-9976-d02bc6f7dcfd.png)

**Comment by newmanls** [comment]
What OS are you using?

**Comment by ArataKamikaze** [comment]
![image](https://user-images.githubusercontent.com/49700094/129393479-df998577-a63e-4801-9ede-9db16f5ad10e.png)

**Comment by newmanls** [comment]
That's weird. I've tried it on W10 and it works fine for me. Have you tried deleting the "chrome" folder and pasting OnelineProton's css again? Also, what version of FF are you using?

**Comment by ArataKamikaze** [comment]
just tried to do that and it didn't fix it, also:
![image](https://user-images.githubusercontent.com/49700094/129437577-14a8a43f-2f18-48d6-83bf-50c0aef9328a.png)

**Comment by newmanls** [comment]
Sorry, but I can figure out your issue. I've checked in W10 and FF 91 but it works just fine to me

**Comment by ArataKamikaze** [comment]
i think i found the problem.
is this the way the popup should appear?
![image](https://user-images.githubusercontent.com/49700094/129458911-88d881db-d7b6-4bb9-a050-541e643ca8b8.png)
 

if so, the problem is in the browser language

**Comment by newmanls** [comment]
Yup. It looks ok now.
