### ISSUE TITLE
How to hidden windows control button

### ISSUE THREAD

**Issue by rustbomber** [lr-tech/OnelineProton#2]
Thank you for share, but I use the theme, the min/max/close button still show. How to hidden them?
![image](https://user-images.githubusercontent.com/437330/132080749-2f7ba570-1789-48fc-b89d-e8196ba14ecb.png)

**Comment by rustbomber** [comment]
And I use this is not working :
![image](https://user-images.githubusercontent.com/437330/132081906-412282d4-f435-499f-b187-8bb0a77bdf87.png)

**Comment by newmanls** [comment]
Try adding this to your css: 
`.titlebar-buttonbox-container { display: none !important }`
If it doesn´t work please let me know and I'll give you some instructions to figure out the solution since I don't have MacOS to check it out.

**Comment by rustbomber** [comment]
> Try adding this to your css:
> `.titlebar-buttonbox-container { display: none !important }`
> If it doesn´t work please let me know and I'll give you some instructions to figure out the solution since I don't have MacOS to check it out.

It is work, thank you.
