### ISSUE TITLE
Pinned tab broken overlap

### ISSUE THREAD

**Issue by quite-frasmotic** [lr-tech/OnelineProton#4]
When a tab is pinned, it overlaps the left-tab-scroll button and there's an odd empty space to the left of it.

**Pinned:**

![2021-10-23T022800](https://user-images.githubusercontent.com/25135963/138537242-8c5c1e63-aef9-4b17-98cb-1c6c4ed2316b.png)

**Unpinned:**

![2021-10-23T022821](https://user-images.githubusercontent.com/25135963/138537250-a62dc642-c037-4618-aa5c-2565bf13e639.png)

(I made sure to test with the original userChrome too, without my small modifications - still present)

**Comment by newmanls** [comment]
Fixed. Thanks for your feedback!
