### ISSUE TITLE
The drop-down bookmark of the bookmarks menu button cannot be clicked with the mouse

### ISSUE THREAD

**Issue by chwt163** [lr-tech/OnelineProton#5]
Your css is very good to use, thank you! 
But when I put the bookmarks menu button next to the address bar, clicking the button will pop up the bookmarks, but not with the mouse, only with the up and down arrow keys

**Comment by chwt163** [comment]
![1](https://user-images.githubusercontent.com/70951194/144537980-05bbabe2-a933-4f95-ab67-71953d2e8b68.png)

**Comment by chwt163** [comment]
Find the problem and delete the following code：

/* animations */

toolbarbutton,

.toolbarbutton-icon,

.subviewbutton,

#urlbar-background,

.urlbar-icon,

#userContext-indicator,

#userContext-label,

.urlbar-input-box, 

#identity-box,

#tracking-protection-icon-container,

[anonid=urlbar-go-button],

.urlbar-icon-wrapper,

#tracking-protection-icon,

#identity-box image,

stack,

vbox,

tab:not(:active) .tab-background,

tab:not([beforeselected-visible])::after,

tab[visuallyselected] .tab-background::before,

tab[visuallyselected] .tab-background::before,

.tab-close-button {

  transition  : var(--animationSpeed) !important;

**Comment by newmanls** [comment]
Fixed. You just had to erase the 'vbox' selector. Thank you for your feedback!
